2018-10-14 20:31:47,991 ERROR: Exception on /edit_profile [POST] [in d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\routes.py", line 96, in edit_profile
    db.session.commit()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\session.py", line 943, in commit
    self.transaction.commit()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\session.py", line 467, in commit
    self._prepare_impl()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\session.py", line 447, in _prepare_impl
    self.session.flush()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
    self._flush(objects)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
    flush_context.execute()
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
    rec.execute(self)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
    uow
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 177, in save_obj
    mapper, table, update)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "d:\mybacktest\50_the-flask-mega-tutorial\venv\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=? WHERE user.id = ?'] [parameters: ('reon777', 4)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-10-14 21:21:01,367 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 21:21:31,686 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 21:22:06,264 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 22:48:33,583 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 22:50:05,577 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 23:06:57,488 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 23:07:55,540 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
2018-10-14 23:51:05,400 INFO: Microblog startup [in D:\Mybacktest\50_The_Flask_Site\The-Flask-Site\app\__init__.py:46]
